### ISSUE TITLE
卧槽，好巧啊......

### ISSUE THREAD

**Issue by s749312025** [he426100/js-wallet#1]
真的是心血来潮点了进来

**Comment by he426100** [comment]
啥？

**Comment by s749312025** [comment]
[http://blog.shengchao.top/article/23](http://blog.shengchao.top/article/23)
这个是我写的，我就是看到之前fork过你的bzz，就点进来看了看，还有没有其他项目，突然发现自己blog的文章，愣了一下。

**Comment by s749312025** [comment]
close
